Repository pydata/pydata-sphinx-theme, pull requests merged in 2023-10, with the labels that each got.

#1517 fix: use 12rambau fork until it's merged with nikeee repo
  .github/workflows/tests.yml
Labels: impact: block-release

#1516 deps: drop support for Sphinx 5
  tools/github_actions_install.sh
Labels: impact: block-release

#1425 Fix duplicate HTML IDs
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/components/version-switcher.html
  src/pydata_sphinx_theme/toctree.py
  tests/test_build/navbar_switcher.html
Labels: tag: accessibility

#1524 Fix font color in search input box
  src/pydata_sphinx_theme/assets/styles/components/_search.scss
Labels: tag: CSS, tag: accessibility

#1525 use event.key for search shortcut
  src/pydata_sphinx_theme/assets/scripts/pydata-sphinx-theme.js
Labels: tag: javascript

#1534 update package-lock.json
  package-lock.json
Labels: kind: maintenance

#1540 kill the docs-live infinite loop (yet again)
  docs/examples/pydata.ipynb
  noxfile.py
  pyproject.toml
Labels: kind: maintenance
