Repository pydata/pydata-sphinx-theme, pull requests merged in 2023-07, with the labels that each got.

#1332 feat: add a scroll to top btn
  src/pydata_sphinx_theme/assets/scripts/bootstrap.js
  src/pydata_sphinx_theme/assets/styles/base/_base.scss
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/layout.html
Labels: kind: enhancement

#1377 MAINT: Miscellaneous improvements to this theme
  README.md
  docs/_static/contributors.yaml
  docs/_static/theme-demo-screenshot.png
  docs/_static/theme_landing.png
  src/pydata_sphinx_theme/assets/styles/abstracts/_links.scss
  src/pydata_sphinx_theme/assets/styles/components/_search.scss
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/sections/header.html
Labels: kind: maintenance

#1376 Fix some CSS header bugs on mobile
  src/pydata_sphinx_theme/assets/styles/components/_search.scss
  src/pydata_sphinx_theme/assets/styles/sections/_header.scss
Labels: kind: bug, tag: CSS

#1373 fix: use consistent markup in examples
  docs/community/topics/page-metadata.md
  docs/user_guide/extending.rst
  docs/user_guide/light-dark.rst
  docs/user_guide/static_assets.md
  docs/user_guide/theme-elements.md
Labels: kind: documentation

#1357 BUG: fix highlighting of current version in switcher menu
  src/pydata_sphinx_theme/assets/scripts/pydata-sphinx-theme.js
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/components/version-switcher.html
  tests/test_a11y.py
  tests/test_build.py
  tests/test_build/navbar_switcher.html
Labels: kind: bug, tag: accessibility, impact: block-release, kind: maintenance

#1379 MAINT: fixes to tabbed examples in docs
  docs/community/topics/page-metadata.md
  docs/user_guide/static_assets.md
  docs/user_guide/theme-elements.md
  src/pydata_sphinx_theme/assets/styles/extensions/_sphinx_design.scss
Labels: kind: documentation, tag: accessibility

#1393 update version JSON config guidance
  docs/user_guide/version-dropdown.rst
Labels: kind: documentation

#1394 Fix version warning banner message
  src/pydata_sphinx_theme/__init__.py
  src/pydata_sphinx_theme/assets/scripts/pydata-sphinx-theme.js
Labels: kind: bug, impact: block-release
