Repository pydata/pydata-sphinx-theme, pull requests merged in 2024-05, with the labels that each got.

#1793 Make announcement banner into a landmark (aside/complementary)
  src/pydata_sphinx_theme/locale/ca/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/cs/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/en/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/es/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/fr/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/ru/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/sphinx.pot
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/sections/announcement.html
Labels: tag: accessibility, tag: component

#1803 Update release action
  .github/workflows/publish.yml
Labels: tag: CI

#1756 Try to implement coverage action instead of using codecov.
  .github/workflows/coverage.yml
  .github/workflows/tests.yml
  pyproject.toml
Labels: kind: enhancement, tag: CI

#1762 Allow paragraph elements to inherit color
  src/pydata_sphinx_theme/assets/styles/base/_base.scss
  src/pydata_sphinx_theme/assets/styles/components/_prev-next.scss
  src/pydata_sphinx_theme/assets/styles/components/header/_header-logo.scss
Labels: tag: CSS

#1770 MAINT: various fixes to print CSS.
  src/pydata_sphinx_theme/assets/styles/components/_versionmodified.scss
  src/pydata_sphinx_theme/assets/styles/content/_admonitions.scss
  src/pydata_sphinx_theme/assets/styles/content/_code.scss
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/components/breadcrumbs.html
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/layout.html
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/sections/announcement.html
Labels: tag: CSS

#1771 Do not generate dropdown in sidebar.
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/sections/sidebar-primary.html
  src/pydata_sphinx_theme/toctree.py
  tests/test_build.py
Labels: kind: enhancement, tag: CSS, tag: component

#1807 DEV - Update pygments tests
  tests/test_build.py
Labels: tag: testing

#1810 Provide copy button container sufficient min height
  src/pydata_sphinx_theme/assets/styles/extensions/_copybutton.scss
Labels: tag: accessibility, tag: component

#1809 purge codecov
  .github/workflows/tests.yml
  codecov.yml
Labels: kind: maintenance, tag: CI

#1757 Implement @smeragoel's table designs
  docs/examples/pydata.ipynb
  src/pydata_sphinx_theme/assets/styles/abstracts/_mixins.scss
  src/pydata_sphinx_theme/assets/styles/content/_tables.scss
  src/pydata_sphinx_theme/assets/styles/extensions/_notebooks.scss
  src/pydata_sphinx_theme/assets/styles/variables/_color.scss
Labels: tag: accessibility

#1820 Remove backwards-compatible text-decoration-skip rule
  src/pydata_sphinx_theme/assets/styles/abstracts/_links.scss
Labels: tag: CSS, kind: maintenance

#1795 fix version-switcher with dirhtml builder
  src/pydata_sphinx_theme/assets/scripts/pydata-sphinx-theme.js
Labels: kind: enhancement, tag: component

#1755 Raise exception for response codes outside range 200-299
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/sections/announcement.html
Labels: kind: enhancement

#1780 Refactor navbar generating function
  src/pydata_sphinx_theme/toctree.py
Labels: tag: component

#1813 Add a pre-commit hook that remove PO files metadata.
  .pre-commit-config.yaml
  src/pydata_sphinx_theme/locale/ca/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/cs/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/en/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/es/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/fr/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/ru/LC_MESSAGES/sphinx.po
Labels: kind: enhancement, tag: i18N

#1808 Animate remotely loaded banners together
  docs/user_guide/announcements.rst
  src/pydata_sphinx_theme/assets/scripts/pydata-sphinx-theme.js
  src/pydata_sphinx_theme/assets/styles/sections/_announcement.scss
  src/pydata_sphinx_theme/locale/ca/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/cs/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/en/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/es/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/fr/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/ru/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/sphinx.pot
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/layout.html
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/sections/announcement.html
  tests/test_build.py
Labels: kind: bug, kind: enhancement

#1763 Track if users has dismissed a version warning banner for a given version.
  src/pydata_sphinx_theme/assets/scripts/pydata-sphinx-theme.js
  src/pydata_sphinx_theme/assets/styles/sections/_announcement.scss
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/sections/announcement.html
Labels: kind: enhancement

#1759 DEV - Refactor CI and environment setup
  .devcontainer/devcontainer.json
  .github/actions/set-dev-env/action.yml
  .github/prerelease-template.md
  .github/workflows/CI.yml
  .github/workflows/prerelease.yml
  .github/workflows/publish.yml
  .github/workflows/tests.yml
  docs/community/setup.md
  docs/community/topics/accessibility.md
  docs/community/topics/assets.md
  docs/community/topics/manual-dev.md
  pyproject.toml
  tests/README.md
  tools/github_actions_install.sh
  tools/profile.py
  tox.ini
Labels: kind: enhancement, tag: dependencies, tag: CI

#1787 Fix keyboard access for scrollable regions created by notebook outputs
  src/pydata_sphinx_theme/assets/scripts/pydata-sphinx-theme.js
  src/pydata_sphinx_theme/assets/styles/extensions/_notebooks.scss
  src/pydata_sphinx_theme/translator.py
  tests/test_a11y.py
Labels: tag: accessibility

#1831 DEV - Update workflows
  .github/workflows/CI.yml
  .github/workflows/prerelease.yml
Labels: kind: enhancement, tag: CI

#1746 Correctly specify the source path to a logo to copy_asset_file
  src/pydata_sphinx_theme/logo.py
Labels: kind: enhancement
