Repository pydata/pydata-sphinx-theme, pull requests merged in 2024-08, with the labels that each got.

#1927 Ensure we use PST colours throughout
  docs/user_guide/web-components.rst
  src/pydata_sphinx_theme/assets/styles/base/_base.scss
  src/pydata_sphinx_theme/assets/styles/content/_code.scss
  src/pydata_sphinx_theme/assets/styles/extensions/_sphinx_design.scss
  src/pydata_sphinx_theme/assets/styles/sections/_announcement.scss
Labels: kind: enhancement, tag: accessibility

#1943 Bump minimum sphinx version.
  pyproject.toml
Labels: tag: dependencies, kind: maintenance

#1942 Make overlay sidebars behave like modals
  src/pydata_sphinx_theme/assets/scripts/pydata-sphinx-theme.js
  src/pydata_sphinx_theme/assets/styles/sections/_sidebar-primary.scss
  src/pydata_sphinx_theme/assets/styles/sections/_sidebar-toggle.scss
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/layout.html
  tests/test_build/sidebar_subpage.html
Labels: tag: accessibility
