Repository pydata/pydata-sphinx-theme, pull requests merged in 2024-01, with the labels that each got.

#1610 Bump minimum Python from 3.8 to 3.9; add 3.12 to CIs
  .github/workflows/prerelease.yml
  .github/workflows/tests.yml
  pyproject.toml
Labels: tag: dependencies, kind: maintenance, tag: CI

#1642 More speedups to section TOC rendering
  src/pydata_sphinx_theme/__init__.py
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/layout.html
  src/pydata_sphinx_theme/toctree.py
Labels: kind: maintenance

#1674 only do security updates for NPM
  .github/dependabot.yml
Labels: kind: maintenance, tag: CI

#1605 Up/down chevrons and "expand"/"collapse" for Sphinx-togglebutton
  babel.cfg
  docs/conf.py
  src/pydata_sphinx_theme/assets/styles/extensions/_togglebutton.scss
  src/pydata_sphinx_theme/locale/ca/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/en/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/es/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/fr/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/ru/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/sphinx.pot
Labels: tag: accessibility

#1585 Keyboard handlers to open and close mobile sidebars
  src/pydata_sphinx_theme/assets/scripts/pydata-sphinx-theme.js
  src/pydata_sphinx_theme/assets/styles/sections/_header.scss
  src/pydata_sphinx_theme/assets/styles/sections/_sidebar-toggle.scss
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/layout.html
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/sections/header.html
Labels: tag: accessibility

#1683 handle null result from queryselector
  src/pydata_sphinx_theme/assets/scripts/pydata-sphinx-theme.js
Labels: kind: bug, tag: javascript
