Repository pydata/pydata-sphinx-theme, pull requests merged in 2024-02, with the labels that each got.

#1698 remove deprecated configs and associated code/tests
  docs/conf.py
  docs/user_guide/branding.rst
  src/pydata_sphinx_theme/__init__.py
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/theme.conf
  tests/sites/base/conf.py
  tests/sites/deprecated/conf.py
  tests/sites/sidebars/conf.py
  tests/sites/test_included_toc/conf.py
  tests/sites/test_navbar_no_in_page_headers/conf.py
  tests/test_build.py
Labels: kind: maintenance

#1711 BUG - Ensure lists markers colours are visible
  src/pydata_sphinx_theme/assets/styles/content/_tables.scss
Labels: kind: bug, tag: CSS

#1687 Fix and change a11y tests
  tests/test_a11y.py
  tests/test_a11y/test_axe_core_chromium__examples_kitchen_sink_admonitions_html__admonitions_dark_.yml
  tests/test_a11y/test_axe_core_chromium__examples_kitchen_sink_admonitions_html__admonitions_light_.yml
  tests/test_a11y/test_axe_core_chromium__examples_kitchen_sink_api_html__api_documentation_dark_.yml
  tests/test_a11y/test_axe_core_chromium__examples_kitchen_sink_api_html__api_documentation_light_.yml
  tests/test_a11y/test_axe_core_chromium__examples_kitchen_sink_blocks_html__blocks_dark_.yml
  tests/test_a11y/test_axe_core_chromium__examples_kitchen_sink_blocks_html__blocks_light_.yml
  tests/test_a11y/test_axe_core_chromium__examples_kitchen_sink_generic_html__generic_items_dark_.yml
  tests/test_a11y/test_axe_core_chromium__examples_kitchen_sink_generic_html__generic_items_light_.yml
  tests/test_a11y/test_axe_core_chromium__examples_kitchen_sink_images_html__images_figures_dark_.yml
  tests/test_a11y/test_axe_core_chromium__examples_kitchen_sink_images_html__images_figures_light_.yml
  tests/test_a11y/test_axe_core_chromium__examples_kitchen_sink_lists_html__lists_dark_.yml
  tests/test_a11y/test_axe_core_chromium__examples_kitchen_sink_lists_html__lists_light_.yml
  tests/test_a11y/test_axe_core_chromium__examples_kitchen_sink_structure_html__structural_elements_2_dark_.yml
  tests/test_a11y/test_axe_core_chromium__examples_kitchen_sink_structure_html__structural_elements_2_light_.yml
  tests/test_a11y/test_axe_core_chromium__examples_kitchen_sink_structure_html__structural_elements_dark_.yml
  tests/test_a11y/test_axe_core_chromium__examples_kitchen_sink_structure_html__structural_elements_light_.yml
  tests/test_a11y/test_axe_core_chromium__examples_kitchen_sink_tables_html__tables_dark_.yml
  tests/test_a11y/test_axe_core_chromium__examples_kitchen_sink_tables_html__tables_light_.yml
  tests/test_a11y/test_axe_core_chromium__examples_kitchen_sink_typography_html__typography_dark_.yml
  tests/test_a11y/test_axe_core_chromium__examples_kitchen_sink_typography_html__typography_light_.yml
  tests/test_a11y/test_axe_core_chromium__examples_pydata_html__pydata_library_styles_dark_.yml
  tests/test_a11y/test_axe_core_chromium__examples_pydata_html__pydata_library_styles_light_.yml
  tests/test_a11y/test_axe_core_chromium__user_guide_extending_html__extending_the_theme_dark_.yml
  tests/test_a11y/test_axe_core_chromium__user_guide_extending_html__extending_the_theme_light_.yml
  tests/test_a11y/test_axe_core_chromium__user_guide_page_toc_html__dark_.yml
  tests/test_a11y/test_axe_core_chromium__user_guide_page_toc_html__light_.yml
  tests/test_a11y/test_axe_core_chromium__user_guide_styling_html__theme_variables_and_css_dark_.yml
  tests/test_a11y/test_axe_core_chromium__user_guide_styling_html__theme_variables_and_css_light_.yml
  tests/test_a11y/test_axe_core_chromium__user_guide_theme_elements_html__theme_specific_elements_dark_.yml
  tests/test_a11y/test_axe_core_chromium__user_guide_theme_elements_html__theme_specific_elements_light_.yml
  tests/test_a11y/test_axe_core_chromium__user_guide_web_components_html__sphinx_design_components_dark_.yml
  tests/test_a11y/test_axe_core_chromium__user_guide_web_components_html__sphinx_design_components_light_.yml
Labels: tag: accessibility, tag: testing

#1703 Do not show announcement banner if announcement contents are empty
  docs/user_guide/announcements.rst
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/sections/announcement.html
Labels: kind: enhancement

#1717 try to fix codecov
  .github/workflows/tests.yml
Labels: kind: maintenance

#1699 fix URLs for dirhtml builds
  src/pydata_sphinx_theme/__init__.py
Labels: kind: bug

#1721 Independently style "Switch to stable version" link
  docs/user_guide/web-components.rst
  src/pydata_sphinx_theme/assets/scripts/pydata-sphinx-theme.js
  src/pydata_sphinx_theme/assets/styles/sections/_announcement.scss
Labels: tag: accessibility
