Repository pydata/pydata-sphinx-theme, pull requests merged in 2024-03, with the labels that each got.

#1726 space icon-links evenly across
  src/pydata_sphinx_theme/assets/styles/components/_icon-links.scss
Labels: tag: CSS

#1633 Fix violation of Axe rule link-name
  docs/_static/gallery.yaml
  docs/examples/gallery.md
  docs/user_guide/web-components.rst
Labels: tag: accessibility

#1707 docs: add the link to the transifex project
  README.md
Labels: kind: documentation
