Repository pydata/pydata-sphinx-theme, pull requests merged in 2024-07, with the labels that each got.

#1905 Fix nbsphinx color outputs, suppress other notebook output Axe errors
  src/pydata_sphinx_theme/assets/styles/extensions/_notebooks.scss
  tests/test_a11y.py
Labels: tag: accessibility

#1914 BUG - Remove schedule trigger for comment action
  .github/workflows/CI.yml
  .github/workflows/publish.yml
Labels: kind: bug, tag: CI

#1929 Change pandoc action
  .github/actions/set-dev-env/action.yml
  .github/workflows/CI.yml
Labels: kind: maintenance, tag: CI

#1928 DEV - Miscellaneous enhancements to CI
  .github/actions/set-dev-env/action.yml
  .github/workflows/CI.yml
  docs/community/setup.md
Labels: tag: dependencies, tag: CI
