Repository pydata/pydata-sphinx-theme, pull requests merged in 2024-12, with the labels that each got.

#2059 Remove hover striping from all but .dataframe tables
  src/pydata_sphinx_theme/assets/styles/abstracts/_mixins.scss
  src/pydata_sphinx_theme/assets/styles/extensions/_notebooks.scss
Labels: tag: accessibility, tag: UX

#2057 DOC - Update documentation regarding formatting files
  .git-blame-ignore-revs
  docs/community/topics/attribution.md
Labels: kind: documentation

#2062 Higher contrast table hover stripe (light mode)
  src/pydata_sphinx_theme/assets/styles/variables/_color.scss
Labels: tag: design, tag: accessibility

#2061 Match Sphinx toggle button and Sphinx Design hover and focus styles
  src/pydata_sphinx_theme/assets/styles/abstracts/_links.scss
  src/pydata_sphinx_theme/assets/styles/abstracts/_mixins.scss
  src/pydata_sphinx_theme/assets/styles/extensions/_sphinx_design.scss
  src/pydata_sphinx_theme/assets/styles/extensions/_togglebutton.scss
  src/pydata_sphinx_theme/assets/styles/variables/_bootstrap.scss
Labels: kind: enhancement

#2072 i18n - Update localisation files
  src/pydata_sphinx_theme/locale/ca/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/cs/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/en/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/es/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/fr/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/it/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/ja/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/ru/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/sphinx.pot
  src/pydata_sphinx_theme/locale/zh/LC_MESSAGES/sphinx.po
Labels: tag: i18N

#2082 BUG - Add `--pst-color-heading` fallback
  src/pydata_sphinx_theme/assets/styles/base/_base.scss
  src/pydata_sphinx_theme/assets/styles/variables/_color.scss
Labels: kind: bug
