Repository pydata/pydata-sphinx-theme, pull requests merged in 2024-09, with the labels that each got.

#1955 ENH - Update bundling and vendoring (JS)
  .gitignore
  package-lock.json
  package.json
  src/pydata_sphinx_theme/assets/scripts/bootstrap.js
  src/pydata_sphinx_theme/assets/scripts/fontawesome.js
  src/pydata_sphinx_theme/assets/styles/bootstrap.scss
  src/pydata_sphinx_theme/assets/styles/pydata-sphinx-theme.scss
  src/pydata_sphinx_theme/assets/styles/variables/_fonts.scss
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/layout.html
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/static/.gitignore
  tests/test_build.py
  webpack.config.js
Labels: kind: enhancement, tag: javascript

#1970 BUG - GH action workflows fixes
  .github/workflows/CI.yml
  .github/workflows/publish.yml
Labels: kind: bug, tag: CI

#1924 A11Y: Add title attribute to theme switcher
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/components/theme-switcher.html
  tests/test_build.py
  tests/test_build/navbar_theme.html
  tests/test_build/sidebar_subpage.html
Labels: kind: enhancement, tag: accessibility

#1959 ENH - Update translations workflows
  .github/workflows/CI.yml
  .github/workflows/prerelease.yml
  .github/workflows/publish.yml
  docs/community/setup.md
  docs/community/topics/i18n.rst
  docs/community/topics/nox.md
  docs/user_guide/i18n.rst
  noxfile.py
  src/pydata_sphinx_theme/locale/ca/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/cs/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/en/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/es/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/fr/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/it/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/ru/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/sphinx.pot
  src/pydata_sphinx_theme/locale/zh/LC_MESSAGES/sphinx.po
  tox.ini
  webpack.config.js
Labels: kind: enhancement, kind: documentation, tag: i18N

#1983 Bolder bigger headings
  src/pydata_sphinx_theme/assets/styles/variables/_fonts.scss
Labels: tag: CSS, tag: accessibility

#1989 ENH add algolia docsearch version meta tag
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/layout.html
Labels: kind: enhancement

#1988 docs: Fix search UI description
  docs/user_guide/search.rst
Labels: kind: documentation

#1982 DEV - Add Fontawesome scripts to build assets
  pyproject.toml
  src/pydata_sphinx_theme/assets/scripts/fontawesome.js
  src/pydata_sphinx_theme/assets/styles/extensions/_sphinx_design.scss
  webpack.config.js
Labels: tag: dependencies, impact: block-release, tag: javascript
