Repository pydata/pydata-sphinx-theme, pull requests merged in 2024-06, with the labels that each got.

#1856 CI - Remove lint from CI
  .github/workflows/CI.yml
Labels: tag: CI

#1849 DOCS: Add navbar_persistent to overview layout
  docs/user_guide/layout.rst
Labels: kind: documentation

#1850 Expose logo_link in theme.conf
  src/pydata_sphinx_theme/__init__.py
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/components/navbar-logo.html
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/theme.conf
Labels: kind: enhancement

#1867 MAINT: Upload nightly wheels and run packaging on PRs and pushes
  .github/workflows/publish.yml
Labels: kind: maintenance, tag: CI

#1860 guard a couple (possibly null) querySelector results
  src/pydata_sphinx_theme/assets/scripts/pydata-sphinx-theme.js
Labels: kind: maintenance, tag: javascript

#1879 BUG - Ensure coverage comment is triggered
  .github/workflows/coverage.yml
  docs/community/practices/versions.md
  docs/user_guide/theme-elements.md
Labels: kind: bug, tag: CI

#1888 Fix url shortening for gitlab, and more test for github
  src/pydata_sphinx_theme/short_link.py
  tests/sites/base/page1.rst
  tests/test_build/gitlab_links.html
  tests/test_short_url.py
Labels: kind: enhancement

#1901 BUG: Ensure coverage comment is properly triggered
  .github/workflows/CI.yml
  .github/workflows/coverage.yml
  tox.ini
Labels: kind: bug, tag: CI

#1861 use ellipsis to truncate breadcrumbs, and test with playwright
  src/pydata_sphinx_theme/assets/styles/components/_breadcrumbs.scss
  src/pydata_sphinx_theme/assets/styles/sections/_header-article.scss
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/components/breadcrumbs.html
  tests/conftest.py
  tests/sites/breadcrumbs/Makefile
  tests/sites/breadcrumbs/_static/emptydarklogo.png
  tests/sites/breadcrumbs/_static/emptylogo.png
  tests/sites/breadcrumbs/conf.py
  tests/sites/breadcrumbs/hansel/gretel/house.rst
  tests/sites/breadcrumbs/index.rst
  tests/sites/breadcrumbs/missing_url.json
  tests/sites/breadcrumbs/switcher.json
  tests/test_a11y.py
  tests/test_playwright.py
Labels: tag: CSS, tag: testing
