Repository pydata/pydata-sphinx-theme, pull requests merged in 2024-04, with the labels that each got.

#1752 DEV - Enable pre-commit ci
  .pre-commit-config.yaml
Labels: tag: dependencies

#1636 Ensure code blocks (<pre>) are keyboard focusable
  src/pydata_sphinx_theme/translator.py
Labels: tag: accessibility

#1758 CI - Swap to trusted publisher for releases
  .github/workflows/publish.yml
Labels: kind: enhancement, tag: CI

#1749 optimize figure bottom margin
  src/pydata_sphinx_theme/assets/styles/content/_figures.scss
Labels: tag: CSS

#1769 tiny CSS change
  docs/user_guide/light-dark.rst
  src/pydata_sphinx_theme/assets/styles/base/_base.scss
  src/pydata_sphinx_theme/assets/styles/extensions/_notebooks.scss
  src/pydata_sphinx_theme/assets/styles/sections/_header.scss
  src/pydata_sphinx_theme/assets/styles/sections/_sidebar-primary.scss
  src/pydata_sphinx_theme/assets/styles/variables/_color.scss
Labels: kind: maintenance

#1564 FEAT - Restyle interactive elements to be more accessible
  .github/workflows/tests.yml
  babel.cfg
  docs/_static/pydata-icon.js
  docs/_static/pydata-logo.png
  docs/conf.py
  docs/examples/gallery.md
  docs/index.md
  docs/user_guide/accessibility.md
  docs/user_guide/styling.rst
  docs/user_guide/web-components.rst
  src/pydata_sphinx_theme/__init__.py
  src/pydata_sphinx_theme/assets/scripts/pydata-sphinx-theme.js
  src/pydata_sphinx_theme/assets/styles/abstracts/_links.scss
  src/pydata_sphinx_theme/assets/styles/base/_base.scss
  src/pydata_sphinx_theme/assets/styles/components/_icon-links.scss
  src/pydata_sphinx_theme/assets/styles/components/_navbar-links.scss
  src/pydata_sphinx_theme/assets/styles/components/_search.scss
  src/pydata_sphinx_theme/assets/styles/components/_switcher-theme.scss
  src/pydata_sphinx_theme/assets/styles/components/_switcher-version.scss
  src/pydata_sphinx_theme/assets/styles/components/_toc-inpage.scss
  src/pydata_sphinx_theme/assets/styles/content/_admonitions.scss
  src/pydata_sphinx_theme/assets/styles/extensions/_copybutton.scss
  src/pydata_sphinx_theme/assets/styles/extensions/_sphinx_design.scss
  src/pydata_sphinx_theme/assets/styles/extensions/_togglebutton.scss
  src/pydata_sphinx_theme/assets/styles/sections/_announcement.scss
  src/pydata_sphinx_theme/assets/styles/sections/_header.scss
  src/pydata_sphinx_theme/assets/styles/sections/_sidebar-primary.scss
  src/pydata_sphinx_theme/assets/styles/sections/_sidebar-toggle.scss
  src/pydata_sphinx_theme/assets/styles/sections/_skip-link.scss
  src/pydata_sphinx_theme/assets/styles/variables/_bootstrap.scss
  src/pydata_sphinx_theme/assets/styles/variables/_layout.scss
  src/pydata_sphinx_theme/locale/ca/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/cs/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/en/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/es/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/fr/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/ru/LC_MESSAGES/sphinx.po
  src/pydata_sphinx_theme/locale/sphinx.pot
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/layout.html
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/sections/header.html
  src/pydata_sphinx_theme/toctree.py
  tests/test_build.py
  tests/test_build/math_header_item.html
  tests/test_build/navbar_ix.html
  tests/test_build/sidebar_subpage.html
  tests/test_build/test_navbar_no_in_page_headers.html
  tests/test_build/test_sidebars_captions.html
  tests/test_build/test_sidebars_nested_page.html
Labels: tag: CSS, tag: accessibility, tag: javascript

#1772 install sphinx test dependencies in all CI testing jobs
  .github/workflows/tests.yml
  pyproject.toml
  tools/github_actions_install.sh
Labels: kind: maintenance, tag: CI

#1786 Fix blockquote color contrasts
  src/pydata_sphinx_theme/assets/styles/content/_quotes.scss
  src/pydata_sphinx_theme/assets/styles/variables/_color.scss
Labels: tag: accessibility
