Repository pydata/pydata-sphinx-theme, pull requests merged in 2025-05, with the labels that each got.

#2204 Fix three separate test failures (a11y, Sphinx dev, Sphinx 7.3)
  .github/workflows/docs.yml
  .github/workflows/lighthouserc.json
  docs/community/inspiration.md
  docs/conf.py
  src/pydata_sphinx_theme/assets/styles/abstracts/_mixins.scss
  src/pydata_sphinx_theme/assets/styles/components/_versionmodified.scss
  src/pydata_sphinx_theme/assets/styles/content/_admonitions.scss
  src/pydata_sphinx_theme/assets/styles/content/_code.scss
  src/pydata_sphinx_theme/assets/styles/content/_quotes.scss
  src/pydata_sphinx_theme/assets/styles/sections/_announcement.scss
  src/pydata_sphinx_theme/assets/styles/variables/_color.scss
  tests/intermittent_warning_list.txt
  tests/sites/base/conf.py
  tests/sites/breadcrumbs/conf.py
  tests/sites/colors/conf.py
  tests/sites/deprecated/conf.py
  tests/sites/sidebars/conf.py
  tests/sites/test_included_toc/conf.py
  tests/sites/test_navbar_no_in_page_headers/conf.py
  tests/sites/version_switcher/conf.py
Labels: kind: bug, tag: CSS, impact: high, tag: accessibility

#2207 MAINT - Fix linkcheck failures
  docs/community/design-system.md
  docs/community/inspiration.md
  docs/community/topics/assets.md
  docs/conf.py
  docs/user_guide/fonts.rst
Labels: kind: bug, tag: CI

#2214 MAINT - Updates to CI workflows
  .github/workflows/CI.yml
  .github/workflows/publish.yml
  docs/community/inspiration.md
  docs/conf.py
  tox.ini
Labels: kind: maintenance, tag: CI
