Repository pydata/pydata-sphinx-theme, pull requests merged in 2025-03, with the labels that each got.

#2141 cleanup UX inspiration page
  docs/_static/inspiration/GitBook-Icon-Dark.svg
  docs/_static/inspiration/docker-mark-blue.svg
  docs/community/inspiration.md
  src/pydata_sphinx_theme/assets/styles/extensions/_gallery_grid.scss
  src/pydata_sphinx_theme/assets/styles/pydata-sphinx-theme.scss
Labels: kind: documentation

#2077 MAINT - CI improvements (security and maintenance)
  .github/actions/set-dev-env/action.yml
  .github/dependabot.yml
  .github/workflows/CI.yml
  .github/workflows/a11y.yml
  .github/workflows/coverage.yml
  .github/workflows/docs.yml
  .github/workflows/prerelease.yml
  .github/workflows/publish.yml
  .github/workflows/rtd-preview-link.yml
  .github/workflows/zizmor.yml
  docs/community/accessibility-statement.md
  docs/community/design-system.md
  docs/community/setup.md
  docs/community/topics/accessibility.md
  docs/community/topics/assets.md
  docs/community/topics/i18n.rst
  docs/conf.py
  docs/user_guide/accessibility.md
  docs/user_guide/fonts.rst
  docs/user_guide/readthedocs.md
  docs/user_guide/styling.rst
  pyproject.toml
  tox.ini
Labels: kind: maintenance, tag: CI

#2097 Fix error during linkcheck when trying to write pygments.css
  src/pydata_sphinx_theme/pygments.py
Labels: kind: bug

#2151 MAINT - Update actions/workflows SHAs
  .github/workflows/CI.yml
  .github/workflows/a11y.yml
  .github/workflows/docs.yml
  .github/workflows/prerelease.yml
  .github/workflows/publish.yml
Labels: tag: dependencies, kind: maintenance, tag: CI

#2111 FIX - Two small bug fixes to search-as-you-type
  src/pydata_sphinx_theme/assets/scripts/pydata-sphinx-theme.js
  src/pydata_sphinx_theme/assets/styles/components/_search.scss
Labels: kind: bug, tag: CSS, tag: javascript, tag: UX

#2161 Unique Playwright trace names to avoid collisions
  .github/workflows/a11y.yml
Labels: tag: CI

#2162 BUG - Update release workflow permissions
  .github/workflows/CI.yml
  .github/workflows/publish.yml
Labels: tag: CI

#2170 BUG - Fix sphinx-design cards borders
  src/pydata_sphinx_theme/assets/styles/extensions/_sphinx_design.scss
Labels: kind: bug, tag: CSS

#2169 Fix miscellaneous issues with CI
  .github/workflows/CI.yml
  .github/workflows/a11y.yml
  .github/workflows/docs.yml
  .github/workflows/zizmor.yml
  docs/community/topics/accessibility.md
  docs/user_guide/theme-elements.md
  tox.ini
Labels: kind: bug, tag: CI

#2174 MAINT - Workflows updates
  .github/workflows/CI.yml
  .github/workflows/coverage.yml
  .github/workflows/rtd-preview-link.yml
  docs/conf.py
Labels: kind: enhancement, tag: CI

#2119 [ENH] Implement new scrollspy
  src/pydata_sphinx_theme/assets/scripts/pydata-sphinx-theme.js
  src/pydata_sphinx_theme/assets/styles/components/_toc-inpage.scss
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/components/page-toc.html
  src/pydata_sphinx_theme/theme/pydata_sphinx_theme/layout.html
  tests/sites/version_switcher/fixture_blocks.rst
  tests/sites/version_switcher/index.rst
  tests/test_playwright.py
Labels: kind: enhancement, tag: javascript, tag: component
