Repository pydata/pydata-sphinx-theme, pull requests merged in 2025-02, with the labels that each got.

#2121 FIX - const reassignment
  src/pydata_sphinx_theme/assets/scripts/pydata-sphinx-theme.js
Labels: kind: bug, tag: javascript

#2120 DOC - clearer logo recommendation
  docs/user_guide/accessibility.md
Labels: kind: documentation

#2122 Upload Playwright trace if test fails
  .github/workflows/CI.yml
  tox.ini
Labels: tag: accessibility, kind: maintenance, tag: CI, tag: testing

#2132 Highlight headings when the user navigates to them
  src/pydata_sphinx_theme/assets/styles/sections/_article.scss
Labels: kind: enhancement, tag: CSS, tag: UX

#2138 MAINT - Update release instructions
  RELEASE.md
Labels: kind: documentation

#2135 [DOC] Create accessibility statement
  docs/community/accessibility-statement.md
  docs/community/index.md
Labels: kind: documentation, tag: accessibility

#2100 Reposition the admonition title icon to the top of the paragraph in m…
  docs/examples/index.rst
  docs/examples/regressions.rst
  src/pydata_sphinx_theme/assets/styles/content/_admonitions.scss
Labels: kind: bug, tag: component
